### ISSUE TITLE
BDB2&3 test segmentation fault

### ISSUE THREAD

**Issue by brucechin** [SabaEskandarian/ObliDB#1]
I can run BDB1 and JOINTEST successfully. But I found that during creating table "uservisits.csv", seg fault will occur at the **first row** calls 

`opOneLinearScanBlock(enclave_id, (int*)&status, structureId2, i, (Linear_Scan_Block*)row, 1);`

Could you check if you can still run BDB2&3 test and load uservisits.csv table without seg fault?

BTW, I also met seg fault if I tries to use google-profiler-tools to profile BDB1 and JOINTEST(just want to find the bottleneck part). Have you ever tried Gperf with SGX enclave before?

**Comment by SabaEskandarian** [comment]
I'm not actively maintaining this code anymore, but I believe those tests were working last I checked. It might be an issue with the processes not having access to enough memory? I unfortunately can't quickly run them now because I don't have access to the computer that has everything installed on it. I haven't tried using Gperf with this before.

**Comment by brucechin** [comment]
i have found the error that i have to use different BLOCK_DATA_SIZE in different test.
