### ISSUE TITLE
Sort-Merge Join

### ISSUE THREAD

**Issue by brucechin** [SabaEskandarian/ObliDB#3]
Hi, I read the sort-merge join code. Basically, you first concatenate two tables and copy join columns to row[BLOCK_DATA_SIZE - 8](length is 4) for sorting. and mark row[BLOCK_DATA_SIZE - 4] 1 or 2 to stand for which table this row comes from : the primary or the foreign.

This means you can only sort INTEGER type column and then do the join. However, for BDB3 query, it joins rankings and uservisits table based on pageURL column which is a VARCHAR(100) type. So I think your sort-merge join is not applicable to BDB3 query.

**Comment by SabaEskandarian** [comment]
Yep, you're right that the sort-merge code as written assumes merging on an integer column. This could be changed by making the comparison check the type of the column and do, e.g., a string comparison instead. 

Our evaluation used the hash join for the BDB3 query. You can see which algorithms each part of the evaluation used by looking at the tests in isv_app/isv_app.cpp. It's a little messy since the choice of algorithm is sometimes made in a parameter passed to the function containing the actual operator code.
